#../run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_wrapper.sh 0 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_idx0.sh
#../run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_wrapper.sh 1 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_idx1.sh
#../run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_wrapper.sh 2 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_idx2.sh
#../run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_wrapper.sh 0 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_idx0.sh
#../run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_wrapper.sh 1 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_idx1.sh
#../run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_wrapper.sh 2 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_idx2.sh
#../run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_wrapper.sh 0 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_idx0.sh
#../run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_wrapper.sh 1 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_idx1.sh
#../run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_wrapper.sh 2 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_idx2.sh
#../run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_wrapper.sh 0 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_idx0.sh
#../run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_wrapper.sh 1 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_idx1.sh
#../run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_wrapper.sh 2 18 15000 50 > run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_idx2.sh
#../run_sample_ddpm_true_pdist_conditional_wrapper.sh 0 18 15000 50 > run_sample_ddpm_true_pdist_conditional_idx0.sh
#../run_sample_ddpm_true_pdist_conditional_wrapper.sh 1 18 15000 50 > run_sample_ddpm_true_pdist_conditional_idx1.sh
#../run_sample_ddpm_true_pdist_conditional_wrapper.sh 2 18 15000 50 > run_sample_ddpm_true_pdist_conditional_idx2.sh

../run_sample_ddpm_true_pdist_conditional_independent_dim_wrapper.sh 0 18 15000 10 > run_sample_ddpm_true_pdist_independent_dim_idx0.sh
../run_sample_ddpm_true_pdist_conditional_independent_dim_wrapper.sh 1 18 15000 10 > run_sample_ddpm_true_pdist_independent_dim_idx1.sh
../run_sample_ddpm_true_pdist_conditional_independent_dim_wrapper.sh 2 18 15000 10 > run_sample_ddpm_true_pdist_independent_dim_idx2.sh

../run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_independent_dim_wrapper.sh 0 18 15000 10 > run_sample_ddpm_sampled_pdist_pred_mean_pred_cov_independent_dim_idx0.sh
../run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_independent_dim_wrapper.sh 1 18 15000 10 > run_sample_ddpm_sampled_pdist_pred_mean_pred_cov_independent_dim_idx1.sh
../run_sample_ddpm_sampled_pdist_conditional_pred_mean_pred_cov_independent_dim_wrapper.sh 2 18 15000 10 > run_sample_ddpm_sampled_pdist_pred_mean_pred_cov_independent_dim_idx2.sh
../run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_independent_dim_wrapper.sh 0 18 15000 10 > run_sample_ddpm_sampled_pdist_pred_mean_true_cov_independent_dim_idx0.sh
../run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_independent_dim_wrapper.sh 1 18 15000 10 > run_sample_ddpm_sampled_pdist_pred_mean_true_cov_independent_dim_idx1.sh
../run_sample_ddpm_sampled_pdist_conditional_pred_mean_true_cov_independent_dim_wrapper.sh 2 18 15000 10 > run_sample_ddpm_sampled_pdist_pred_mean_true_cov_independent_dim_idx2.sh
../run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_independent_dim_wrapper.sh 0 18 15000 10 > run_sample_ddpm_sampled_pdist_true_mean_pred_cov_independent_dim_idx0.sh
../run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_independent_dim_wrapper.sh 1 18 15000 10 > run_sample_ddpm_sampled_pdist_true_mean_pred_cov_independent_dim_idx1.sh
../run_sample_ddpm_sampled_pdist_conditional_true_mean_pred_cov_independent_dim_wrapper.sh 2 18 15000 10 > run_sample_ddpm_sampled_pdist_true_mean_pred_cov_independent_dim_idx2.sh
../run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_independent_dim_wrapper.sh 0 18 15000 10 > run_sample_ddpm_sampled_pdist_true_mean_true_cov_independent_dim_idx0.sh
../run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_independent_dim_wrapper.sh 1 18 15000 10 > run_sample_ddpm_sampled_pdist_true_mean_true_cov_independent_dim_idx1.sh
../run_sample_ddpm_sampled_pdist_conditional_true_mean_true_cov_independent_dim_wrapper.sh 2 18 15000 10 > run_sample_ddpm_sampled_pdist_true_mean_true_cov_independent_dim_idx2.sh

